-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 20:39:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema botanica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `botanica` ;

-- -----------------------------------------------------
-- Schema botanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `botanica` DEFAULT CHARACTER SET utf8 ;
USE `botanica` ;

-- -----------------------------------------------------
-- Table `botanica`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`roles` ;

CREATE TABLE IF NOT EXISTS `botanica`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` INT(50) NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `botanica`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`usuario` ;

CREATE TABLE IF NOT EXISTS `botanica`.`usuario` (
  `id` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `id_roles` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `roles_fk`
    FOREIGN KEY (`id_roles`)
    REFERENCES `botanica`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `botanica`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`persona` ;

CREATE TABLE IF NOT EXISTS `botanica`.`persona` (
  `id` INT NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `edad` INT NOT NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_fk_idx` (`id_usuarios` ASC),
  CONSTRAINT `usuario_fk`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `botanica`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `botanica`.`temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`temas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`temas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `botanica`.`preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`preguntas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `cerrado` TINYINT NOT NULL,
  `texto` TEXT(255) NOT NULL,
  `id_temas` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `temas_id`
    FOREIGN KEY (`id_temas`)
    REFERENCES `botanica`.`temas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `usuarios_id`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `botanica`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `botanica`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`user` ;

CREATE TABLE IF NOT EXISTS `botanica`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `botanica`.`respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`respuestas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `id_usuario` INT NOT NULL,
  `respuestascol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `preguntas_id`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `botanica`.`preguntas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `botanica`.`clima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`clima` ;

CREATE TABLE IF NOT EXISTS `botanica`.`clima` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `botanica`.`suelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`suelos` ;

CREATE TABLE IF NOT EXISTS `botanica`.`suelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `botanica`.`plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`plantas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`plantas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mes_inicio` DATE NOT NULL,
  `mes_fin` DATE NOT NULL,
  `id_suelo` INT NOT NULL,
  `id_clima` INT NOT NULL,
  `descripcion` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_clima_idx` (`id_clima` ASC),
  INDEX `id_suelo_idx` (`id_suelo` ASC),
  CONSTRAINT `id_clima`
    FOREIGN KEY (`id_clima`)
    REFERENCES `botanica`.`clima` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_suelo`
    FOREIGN KEY (`id_suelo`)
    REFERENCES `botanica`.`suelos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `botanica`.`tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`tipos` ;

CREATE TABLE IF NOT EXISTS `botanica`.`tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = ndbcluster
COMMENT = '			';


-- -----------------------------------------------------
-- Table `botanica`.`tipos_plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`tipos_plantas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`tipos_plantas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipos` INT NOT NULL,
  `id_plantas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_tipos_idx` (`id_tipos` ASC),
  INDEX `id_plantas_idx` (`id_plantas` ASC),
  CONSTRAINT `id_tipos`
    FOREIGN KEY (`id_tipos`)
    REFERENCES `botanica`.`tipos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_plantas`
    FOREIGN KEY (`id_plantas`)
    REFERENCES `botanica`.`plantas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `botanica`.`etapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`etapas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`etapas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(512) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `botanica`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`estados` ;

CREATE TABLE IF NOT EXISTS `botanica`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `botanica`.`usuario_planta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`usuario_planta` ;

CREATE TABLE IF NOT EXISTS `botanica`.`usuario_planta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_planta` INT NOT NULL,
  `id_etapa` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `remedio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_etapas_idx` (`id_etapa` ASC),
  INDEX `id_estados_idx` (`id_estado` ASC),
  CONSTRAINT `id_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `botanica`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_plantas`
    FOREIGN KEY (`id_planta`)
    REFERENCES `botanica`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_etapas`
    FOREIGN KEY (`id_etapa`)
    REFERENCES `botanica`.`etapas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_estados`
    FOREIGN KEY (`id_estado`)
    REFERENCES `botanica`.`estados` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
